// admin/pages/login.vue
<template>
  <page-center>
    <v-card width="450" flat>
      <v-card-title>
        <v-row class="mb-4" no-gutters>
          <v-col class="d-flex justify-center mb-2" md="12">
            <v-avatar size="80">
              <app-image
                :size="80"
                src="/tup-logo.png"
                alt="Technological University of the Philippines"
              />
            </v-avatar>
          </v-col>
          <v-col>
            <h1
              class="headline text-center w-100"
              style="word-break: break-word"
            >
              Technological University of the Philippines <br />
              <span class="font-weight-bold">Voting System</span>
            </h1>
          </v-col>
        </v-row>
      </v-card-title>
      <login-form v-if="success"></login-form>
      <login-verification-code-form v-else />
    </v-card>
  </page-center>
</template>

<script lang="ts">
import LoginForm from "~/components/pages/login/forms/LoginForm.vue";
import LoginVerificationCodeForm from "~/components/pages/login/forms/LoginVerificationCodeForm.vue";
import PageCenter from "@/components/utils/PageCenter.vue";
import Vue from "vue";
import { AdminLoginReturn } from "../services/auth.service";

export default Vue.extend({
  auth: "guest",
  layout: "basic",

  components: {
    LoginForm,
    LoginVerificationCodeForm,
    PageCenter,
  },
  head: {
    title: "Admin Login",
  },
  data() {
    return {
      success: null as AdminLoginReturn | null,
    };
  },

  methods: {
    setSuccess(data: AdminLoginReturn) {
      this.success = data;
    },
  },
});
</script>

// web/pages/admin/login.tsx
import { Avatar, Box, Typography } from "@mui/material";
import React from "react";
import LoginForm from "../../src/components/admin/forms/LoginForm";
import DefaultLayout from "../../src/layouts/DefaultLayout";

interface LoginPageProps {}

const LoginPage: AdminNextPage<LoginPageProps> = ({}) => {
  return (
    <DefaultLayout>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          height: "100vh",
        }}>
        <Box
          sx={{
            display: "flex",
            minWidth: 450,
            width: 450,
            alignItems: "center",
            justifyContent: "center",
            flexDirection: "column",
          }}>
          <Avatar
            alt="TUP Logo"
            sx={{
              height: 100,
              width: 100,
            }}
            src="/img/tup-logo.png"
          />

          <Typography
            sx={{ textAlign: "center", mt: 1, px: 2, mb: 4 }}
            variant="h5">
            Technological University of the Philippines
            <br />
            <b>Voting System</b>
          </Typography>

          <LoginForm />
        </Box>
      </Box>
    </DefaultLayout>
  );
};

// LoginPage.auth = un;

export default LoginPage;
